### ISSUE TITLE
Rename file with correct extension

### ISSUE THREAD

**Issue by xplosionmind** [scambifestival/scambi.org#26]
Occhio @2ale2, the correct file extension for `toUpdate` is `.yml` or `.yaml`, as the format I suggested to use is [YAML](https://yaml.org).

**Comment by xplosionmind** [comment]
I suggest to fill the file like this:

```
tables:
  - relations
  - libro-soci
  - 2022-labs
  - 2022-pinoli
  - etc…
```

**Comment by 2ale2** [comment]
Ok, sorry that's the first time I work YAML.

**Comment by xplosionmind** [comment]
we continue dealing with this in the dedicated repository
